services:
  - type: web
    name: pham-minh-chien-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PIN
        value: ChienPR
